/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Paneles.PanelPacientes;
import Paneles.PanelUsuarios;
import java.awt.Button;
import java.awt.Dimension;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.GridLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author fknrk
 */
public class VistaPrincipal extends javax.swing.JFrame {
 int monitorWidth;
  int monitorHeight;
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();        
           GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment()
            .getDefaultScreenDevice();
        monitorWidth = Math.round(gd.getDisplayMode().getWidth());
        monitorHeight = Math.round(gd.getDisplayMode().getHeight());
        Dimension dim = new Dimension(monitorWidth, monitorHeight);
        this.setPreferredSize(dim);
        InicializaPaneles(monitorWidth,monitorHeight);
        this.setBounds(0, 0,monitorWidth,monitorHeight - 50);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.add(pnlSuperior);
     
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }
    
      private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:

     MuestraPaneles(pnlUsuarios,1300,700);
    }                                           

        private void btnVisitasActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:

     MuestraPaneles(pnlPacientes,1300,700);
    }     
    
    public void InicializaPaneles(int width,int height){
        GridLayout layout = new GridLayout(10, 1);     
        JButton btnInicio = new JButton();
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users.png")));
        btnInicio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesHover/users.png")));
        btnInicio.setOpaque(true);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setBorderPainted(true);
        btnInicio.setToolTipText("Usuarios");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        
        JButton btnVisitas = new JButton();
        btnVisitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/paciente.png")));
        btnVisitas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesHover/paciente.png")));
        btnVisitas.setOpaque(true);
        btnVisitas.setContentAreaFilled(false);
        btnVisitas.setBorderPainted(true);
        btnVisitas.setToolTipText("Pacientes");
        btnVisitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitasActionPerformed(evt);
            }
        });
        
        
        
        
        
        
        pnlLateral.setLayout(layout);
        pnlLateral.add(btnInicio);
        pnlLateral.add(btnVisitas);
        pnlSuperior.setBounds(0, 0, width, 50);
        pnlSuperior.setBackground(new java.awt.Color(100, 100, 255));
        pnlLateral.setBounds(0, 50, 100, height);
        pnlLateral.setBackground(new java.awt.Color(100, 100, 255));
        this.add(pnlLateral);
        this.add(pnlSuperior);
    }
    public void MuestraPaneles(JPanel panel,int width,int height){
     this.add(panel);
     OcultaPaneles();
     panel.setBounds(100, 50, width, height);
     //pnlUsuarios.setBackground(new java.awt.Color(0, 0, 255));
     panel.setVisible(true);
     repaint();
    }
    
    public void OcultaPaneles(){
        pnlUsuarios.setVisible(false);
        pnlPacientes.setVisible(false);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
JPanel pnlLateral = new JPanel();
JPanel pnlSuperior = new JPanel();
JPanel pnlUsuarios = new PanelUsuarios();
JPanel pnlPacientes = new PanelPacientes();
}
